/*
 * ClickBand Junior — MelodicRhythmGenerator.js
 * Bar-safe melodic rhythms. Output contract compatible with version 2.
 * Copyright (c) 2026 Fabio Albanese
 * SPDX-License-Identifier: CC-BY-NC-4.0
 */
"use strict";
(function(global){
  function clone(a){return a.slice();}
  function sig(a){return a.join("-");}
  function phraseSig(b){return b.map(sig).join("|");}
  function choice(a,r){if(!a.length)throw new Error("Lista ritmica vuota.");return a[Math.floor(r()*a.length)];}
  function weighted(items,r){var total=0,i;for(i=0;i<items.length;i++)total+=Math.max(0,items[i].weight||0);if(total<=0)return items[0].value;var x=r()*total;for(i=0;i<items.length;i++){x-=Math.max(0,items[i].weight||0);if(x<=0)return items[i].value;}return items[items.length-1].value;}
  function enforce(starts,required){var s=clone(starts).sort(function(a,b){return a-b;}),o=[];for(var i=0;i<s.length;i++){var v=s[i];if(v<0||v>15||v%2)continue;if(!o.length||v-o[o.length-1]>=2)o.push(v);}if(!o.length||o[0]!==0)o.unshift(0);if(required!==undefined&&o.indexOf(required)<0){while(o.length&&required-o[o.length-1]<2)o.pop();o.push(required);}return o;}
  function distance(a,b){var A={},B={},c=0,i;for(i=0;i<a.length;i++)A[a[i]]=1;for(i=0;i<b.length;i++)B[b[i]]=1;for(i=0;i<a.length;i++)if(B[a[i]])c++;return(a.length-c)+(b.length-c);}
  function MelodicRhythmGenerator(config){
    config=config||{};this.style=String(config.style||"POP").toUpperCase();this.memorySize=(Number.isInteger(config.memorySize)&&config.memorySize>0)?config.memorySize:18;this.random=typeof config.random==="function"?config.random:Math.random;this.storageKey="clickband.melodicRhythmHistory.v2."+this.style;this.allowedDurations=[2,4,8,16];this.lastABySection={};
    this.patterns={
      sparse:[[0,8],[0,6,12],[0,4,12],[0,10],[0,6,10],[0,4,10],[0,8,12],[0,4,8],[0,6,10,14]],
      regular:[[0,4,8,12],[0,2,8,12],[0,4,8,14],[0,6,8,14],[0,2,6,10,14],[0,4,6,10,14],[0,2,6,10,12],[0,4,8,12,14],[0,6,8,12,14],[0,4,10,12]],
      syncopated:[[0,2,6,10,14],[0,2,8,10,14],[0,6,8,12,14],[0,4,8,12,14],[0,2,8,12,14],[0,4,8,10,14],[0,6,10,12,14]],
      flowing:[[0,2,6,10,14],[0,4,8,10,14],[0,2,8,12,14],[0,4,8,12,14],[0,2,6,10,14]]
    };
    this.durationWeights={sparse:{2:1,4:2,8:5,16:2},regular:{2:2,4:5,8:3,16:1},syncopated:{2:4,4:5,8:2,16:1},flowing:{2:5,4:5,8:1,16:1}};
  }
  MelodicRhythmGenerator.prototype.getHistory=function(){try{var raw=global.localStorage&&global.localStorage.getItem(this.storageKey),p=raw?JSON.parse(raw):[];return Array.isArray(p)?p:[];}catch(e){MelodicRhythmGenerator.memory=MelodicRhythmGenerator.memory||{};return MelodicRhythmGenerator.memory[this.storageKey]||[];}};
  MelodicRhythmGenerator.prototype.saveHistory=function(h){h=h.slice(-this.memorySize);try{if(global.localStorage)global.localStorage.setItem(this.storageKey,JSON.stringify(h));}catch(e){MelodicRhythmGenerator.memory=MelodicRhythmGenerator.memory||{};MelodicRhythmGenerator.memory[this.storageKey]=h;}};
  MelodicRhythmGenerator.prototype.familiesFor=function(sectionName){var s=String(sectionName||"verse").toLowerCase();if(s==="intro"||s==="outro")return["sparse","regular"];if(s==="chorus"||s==="only"){if(this.style==="FOLK")return["regular","flowing","sparse"];if(this.style==="LATIN"||this.style==="JAZZ")return["syncopated","flowing","regular"];if(this.style==="BLUES")return["syncopated","sparse","regular"];if(this.style==="CELTIC")return["flowing","regular","syncopated"];return["regular","flowing","syncopated"];}if(s==="bridge"){if(this.style==="FOLK")return["sparse","regular","syncopated"];if(this.style==="LATIN")return["syncopated","regular","flowing"];if(this.style==="JAZZ")return["flowing","syncopated","sparse"];if(this.style==="BLUES")return["sparse","syncopated","regular"];return["syncopated","sparse","regular"];}if(this.style==="FOLK")return["regular","sparse","flowing"];if(this.style==="LATIN"||this.style==="JAZZ")return["syncopated","flowing","regular"];if(this.style==="BLUES")return["syncopated","sparse","regular"];if(this.style==="CELTIC")return["flowing","regular","syncopated"];return["regular","sparse","syncopated"];};
  MelodicRhythmGenerator.prototype.pickMainFamily=function(f){return weighted(f.map(function(x,i){return{value:x,weight:i===0?6:(i===1?3:1)};}),this.random);};
  MelodicRhythmGenerator.prototype.pickPattern=function(families,excluded,recentFirst,isFirst){var c=[];for(var fi=0;fi<families.length;fi++){var fam=families[fi],bank=this.patterns[fam]||[];for(var p=0;p<bank.length;p++){var pat=bank[p];if(excluded.indexOf(sig(pat))>=0)continue;if(isFirst){var close=false;for(var r=0;r<recentFirst.length;r++)if(distance(pat,recentFirst[r])<=2){close=true;break;}if(close)continue;}c.push({value:{family:fam,starts:pat},weight:fi===0?4:(fi===1?2:1)});}}if(!c.length){for(fi=0;fi<families.length;fi++){fam=families[fi];bank=this.patterns[fam]||[];for(p=0;p<bank.length;p++)c.push({value:{family:fam,starts:bank[p]},weight:1});}}var x=weighted(c,this.random);return{family:x.family,starts:enforce(x.starts)};};
  MelodicRhythmGenerator.prototype.makeVariation=function(starts){var o=clone(starts),op=choice(["shift","remove","insert","density"],this.random),i,v,avail;if(op==="shift"&&o.length>2){i=1+Math.floor(this.random()*(o.length-1));v=Math.max(2,Math.min(14,o[i]+choice([-2,2],this.random)));if(o.indexOf(v)<0&&v-o[i-1]>=2&&(i===o.length-1||o[i+1]-v>=2))o[i]=v;}else if((op==="remove"||op==="density")&&o.length>3)o.splice(1+Math.floor(this.random()*(o.length-1)),1);else{avail=[2,4,6,8,10,12,14].filter(function(x){for(var j=0;j<o.length;j++)if(Math.abs(o[j]-x)<2)return false;return true;});if(avail.length)o.push(choice(avail,this.random));}return enforce(o);};
  MelodicRhythmGenerator.prototype.makeBFromA=function(a,section){var out=[];for(var b=0;b<3;b++){var v=this.makeVariation(a[b]||[0,4,8,12]);if(sig(v)===sig(a[b]||[]))v=this.makeVariation(a[b]||[0,4,8,12]);out.push(v);}var long=section==="outro"||this.random()<0.48;out.push(long?[0]:enforce(this.makeVariation(a[3]||[0,4,8]).filter(function(x){return x<=8;}),8));return out;};
  MelodicRhythmGenerator.prototype.chooseDuration=function(start,next,finalBar,closing,family,variant){var gap=(next===undefined?16:next)-start,allowed=this.allowedDurations.filter(function(d){return d<=gap;});if(!allowed.length)throw new Error("Spazio ritmico non valido: "+gap+" spot.");if(closing&&finalBar&&allowed.indexOf(gap)>=0)return gap;var w=this.durationWeights[family]||this.durationWeights.regular,pool=[];for(var i=0;i<allowed.length;i++){var d=allowed[i],n=(w[d]||1)+((variant==="B"&&(d===8||d===16))?1:0);for(var j=0;j<n;j++)pool.push(d);}return choice(pool,this.random);};
  MelodicRhythmGenerator.prototype.toEvents=function(starts,finalBar,family,variant){var out=[];for(var i=0;i<starts.length;i++){var closing=!!(finalBar&&i===starts.length-1);out.push({start:starts[i],duration:this.chooseDuration(starts[i],starts[i+1],finalBar,closing,family,variant),isClosingNote:closing});}return out;};
  MelodicRhythmGenerator.prototype.generate=function(sectionName,variant){variant=String(variant||"A").toUpperCase();var key=String(sectionName||"verse").toLowerCase(),families=this.familiesFor(sectionName),main=this.pickMainFamily(families),history=this.getHistory(),recentFirst=[],recentPhrases=[];for(var h=0;h<history.length;h++){if(history[h]&&Array.isArray(history[h].firstBar))recentFirst.push(history[h].firstBar);if(history[h]&&typeof history[h].phrase==="string")recentPhrases.push(history[h].phrase);}var bars,fams,full;
    if(variant==="B"&&this.lastABySection[key]){var A=this.lastABySection[key];bars=this.makeBFromA(A.bars,sectionName);fams=A.fams.slice();main=A.main;full=phraseSig(bars);for(var va=0;recentPhrases.indexOf(full)>=0&&va<8;va++){bars=this.makeBFromA(A.bars,sectionName);full=phraseSig(bars);}}
    else{for(var attempt=0;attempt<24;attempt++){bars=[];fams=[];var used=[];for(var b=0;b<3;b++){var allowed=b===0?[main]:[main].concat(families.filter(function(x){return x!==main;})),pick=this.pickPattern(allowed,used,recentFirst,b===0);bars.push(pick.starts);fams.push(pick.family);used.push(sig(pick.starts));}var long=sectionName==="outro"||this.random()<0.42;bars.push(long?[0]:enforce(choice([[0,4,8],[0,2,8],[0,6,8]],this.random),8));fams.push(main);full=phraseSig(bars);if(recentPhrases.indexOf(full)<0)break;}}
    if(variant==="A")this.lastABySection[key]={main:main,bars:bars.map(clone),fams:fams.slice()};history.push({firstBar:bars[0].slice(),phrase:full,section:key,variant:variant,family:main});this.saveHistory(history);var counts={},outFamily=main,best=-1;for(var i=0;i<fams.length;i++){counts[fams[i]]=(counts[fams[i]]||0)+1;if(counts[fams[i]]>best){best=counts[fams[i]];outFamily=fams[i];}}return{family:outFamily,signatures:bars.map(sig),phraseSignature:full,bars:bars.map(function(starts,index){return this.toEvents(starts,index===3,fams[index]||outFamily,variant);},this)};
  };
  global.MelodicRhythmGenerator=MelodicRhythmGenerator;
})(window);
